name: test-gh
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'examples/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'examples/**'

jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/k14s/kbld
    - name: Run Tests
      run: |
        set -e -x

        # Install ytt, kapp for build and tests
        mkdir -p /tmp/bin
        export PATH=/tmp/bin:$PATH

        wget -O- https://k14s.io/install.sh | K14SIO_INSTALL_BIN_DIR=/tmp/bin bash

        wget -O- https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-linux-amd64 > /tmp/bin/minikube
        chmod +x /tmp/bin/minikube
        minikube start --driver=docker --insecure-registry=172.17.0.0/16
        eval $(minikube docker-env --shell=bash)

        # Ensure that there is no existing kbld installed
        rm -f /tmp/bin/kbld

        git config --global user.email "dummy@k14s.io"
        git config --global user.name "Dummy dummy"

        wget -O- https://github.com/buildpacks/pack/releases/download/v0.8.1/pack-v0.8.1-linux.tgz > /tmp/pack-cli.tgz
        tar xzvf /tmp/pack-cli.tgz -C /tmp/bin

        export GOPATH=$(echo `pwd`)
        cd src/github.com/k14s/kbld

        ./hack/test-all-minikube-local-registry.sh
        ./hack/build-binaries.sh
